#! /usr/bin/env python

from ur5_kdl_solver.force_generator import random_force_generator

if __name__ == '__main__':
    try:
        random_force_generator()
    except KeyboardInterrupt:
        exit(1)
